### ISSUE TITLE
how to make a geometry only with the stroke without fill. and how to set the width/color of stroke

### ISSUE THREAD

**Issue by BraverChiang** [nicklockwood/Euclid#1]

**Comment by nicklockwood** [comment]
@BraverChiang currently this isn't supported. SceneKit doesn't support stroke width or colour for lines, so I don't really have a way to render these options even if Euclid supported them.

In future I intend to support paths with holes, which would allow you to create a filled shape with thin border, but right now that's difficult to do using the built-in primitives.

**Comment by andygeers** [comment]
It may or may not suit your purposes, but I used [SCNLine](https://github.com/maxxfrazer/SceneKit-SCNLine)

**Comment by andygeers** [comment]
(it might be overkill, but I then also use [SwiftGraph](https://github.com/davecom/SwiftGraph) to find all of the unique edges in the mesh, to work out where I need to draw a line)

**Comment by nicklockwood** [comment]
Euclid now has the option to extrude a shape along a path, so you can achieve a similar effect to SCNLine by extruding a circle along your path.
