### ISSUE TITLE
Union only outer part

### ISSUE THREAD

**Issue by PrashantKT** [nicklockwood/Euclid#100]
Hi @nicklockwood  

Hope you are doing well 

I wanted to union 

MAIN NODE with all children 
<img width="824" alt="Screenshot 2022-12-23 at 8 40 02 PM" src="https://user-images.githubusercontent.com/35359315/209358176-719084d5-5eae-46e4-ab31-52d78bbd8661.png">

But I wanted only outer  area to be union  not fully 

Below is the top view  After union child node is fully added to main node 

<img width="916" alt="Screenshot 2022-12-23 at 8 39 51 PM" src="https://user-images.githubusercontent.com/35359315/209358931-eb862b8d-147c-44d3-a77b-371d8a666e6a.png">

But What I need is only outer area

**Comment by nicklockwood** [comment]
I'm afraid I don't understand what you mean by the "outer area"

**Comment by PrashantKT** [comment]
Hi @nicklockwood  

In short what I need is 

Main Node + Node 1  (Tooth)

where node 1's only border will be used in union 

so   If I cut the model from center - Node1 (tooth) will have empty area not solid

**Comment by nicklockwood** [comment]
@PrashantKT au, I understand. This is how the union command works already, but only if both models are watertight, otherwise it cannot tell which is the outside surface. I'm guessing if the models are based on scan data they probably have holes?

Can you share the models? I might be able to find a solution for your specific case.

**Comment by PrashantKT** [comment]
[Archive.zip](https://github.com/nicklockwood/Euclid/files/10304381/Archive.zip)

Here are the files 

I want t8.stl file with border only (outer area )

**Comment by nicklockwood** [comment]
@PrashantKT hi, I tried taking a union of your two models and it appears that it's doing the correct thing already. Did you try it?

```swift
jaw.union(tooth)
```

**Comment by nicklockwood** [comment]
Here is the model cut through the center of the tooth - see that just the outer surface remains.

<img width="812" alt="Screenshot 2022-12-26 at 20 40 13" src="https://user-images.githubusercontent.com/546885/209582208-437fdb21-091e-4931-9ec2-80453f4424fa.png">

**Comment by PrashantKT** [comment]
I think I couldn't explain the requirements 

Right now the tooth is solid geometry  For example Filled box 

What I need is empty from inside for example box with sides only empty  inside 

I don't know technical term in 3d Geometry may be it is faces 

![d-black-empty-box-frame-isolated-white-background-clipping-path-inside-91388626](https://user-images.githubusercontent.com/35359315/209813635-e328d28f-8f72-4fdd-8ff5-e57416f1ec71.jpg)

**Comment by nicklockwood** [comment]
@PrashantKT there is no solid geometry in Euclid. Everything is a hollow shell.

How are you doing the cut through the model? By default Euclid will fill in cut surfaces, so it may appear that it is solid. In the screenshot above I used clip with nil material to prevent it filling the hole.

**Comment by PrashantKT** [comment]
@nicklockwood  Got your point let me check it again , may be  the problem is somewhere  else
