### ISSUE TITLE
Is it possible to use with Objective C ?

### ISSUE THREAD

**Issue by unnamed666** [nicklockwood/Euclid#11]
i installed it with pod to my project but cant figure out how to use it - is it even possible ?

**Comment by nicklockwood** [comment]
@unnamed666 Euclid isn't designed to be used with Objective-C. What you could do is write a wrapper in Swift that imports Euclid and exports whatever functionality you need as `@objc` class interfaces that can be called from Objective-C code.

**Comment by unnamed666** [comment]
thank you - i'am trying it right now :)
