### ISSUE TITLE
importing STL file to Euclid.

### ISSUE THREAD

**Issue by chessdenman** [nicklockwood/Euclid#110]
Sorry for a raft of very basic questions

I am importing an STL file into Euclid using the script below 

I am finding I can only see the mesh if I uncomment out the debug line. With that line uncommented I see the bounding box and the red imported mesh.

The STL file being imported is a standard one in plain text actually created from a program called onshape.

Can anyone help me with what I am doing wrong.

:

```swift
import SwiftUI
import SceneKit
import Euclid
import UniformTypeIdentifiers

struct ContentView: View {
    var body: some View {
      SceneKitView()
            
    }
}

// UIViewRepresentable to integrate SCNView into SwiftUI
struct SceneKitView: NSViewRepresentable {
    func updateNSView(_ nsView: SCNView, context: Context) {
        
    }
    func getCameraPosition(for node: SCNNode) -> SCNVector3 {
        // Calculate the bounding box of the node
        let bBox = node.boundingBox
        let maxVec = bBox.max
        let minVec = bBox.min
        
        print(maxVec)
        print(minVec)

            // Calculate the center of the bounding box
        let boundingBoxCenter = SCNVector3(
            x: (maxVec.x + minVec.x) / 2.0,
            y: (maxVec.y + minVec.y) / 2.0,
            z: (maxVec.z + minVec.z) / 2.0
        )
        
        // Determine the distance of the camera from the center of the bounding box
        let boundingBoxSize = SCNVector3(
            x: maxVec.x - minVec.x,
            y: maxVec.y - minVec.y,
            z: maxVec.z - minVec.z
        )
        let maxDimension = max(boundingBoxSize.x, boundingBoxSize.y, boundingBoxSize.z)
        let cameraDistance = maxDimension * 2.0 // Example multiplier to ensure geometry is visible
        
            // Calculate the camera position
        let cameraPosition = SCNVector3(boundingBoxCenter.x, boundingBoxCenter.y, boundingBoxCenter.z + cameraDistance)
        
        print(cameraPosition)
            
        return cameraPosition

        }
    

    func makeNSView(context: Context) -> SCNView {
        let scnView = SCNView()
        // Set up your SceneKit scene here
        let scene = SCNScene()
        scnView.scene = scene
        
        let cameraNode = SCNNode()
        cameraNode.camera = SCNCamera()
        scene.rootNode.addChildNode(cameraNode)
        
        
        let openPanel = NSOpenPanel()
        openPanel.prompt = "Select STL file"
        openPanel.allowedContentTypes = [UTType(filenameExtension: "stl")].compactMap { $0 }

        openPanel.allowsMultipleSelection = false
        openPanel.begin {(result) in
            if result == .OK, let fileURL = openPanel.url {
                
                do {
                    let mesh = try(Mesh(url:fileURL,ignoringTransforms: true))
                    print(mesh.polygons.count)
                    let material = SCNMaterial()
                    material.diffuse.contents = NSColor.red
                    let geometry = SCNGeometry(mesh)
                    geometry.materials = [material]
                    let meshNode = SCNNode(geometry: geometry)
                    scene.rootNode.addChildNode(meshNode)
                    cameraNode.position = getCameraPosition(for: meshNode)
                    let constraint = SCNLookAtConstraint(target: meshNode)
                    cameraNode.constraints = [constraint]
                } catch {
                    print("Error loading file")
                }
            }
        }
     
            


        scnView.scene = scene
        scnView.autoenablesDefaultLighting = true
        scnView.allowsCameraControl = true
        scnView.backgroundColor = .gray
        scnView.showsStatistics = true
        //scnView.debugOptions = [.showBoundingBoxes,]
        
        
        return scnView
    }
}
```

**Comment by nicklockwood** [comment]
@chessdenman my suspicion is that this is a SceneKit issue rather than anything related to Euclid. What happens if you just load the STL file directly using SNCScene.init(url:)? https://developer.apple.com/documentation/scenekit/scnscene/1522660-init

**Comment by nicklockwood** [comment]
I tried your code and it seemed to work fine for the couple of STL files I tested. Can you share the specific file you are trying to load? Perhaps there is something unusual about it?

**Comment by chessdenman** [comment]
wow that is so kind of you
Here is the file
I am such a beginner that if chatGPT can't help me out I get a bit stuck

Chess Denman

**Comment by nicklockwood** [comment]
@chessdenman the file wasn't attached - you might need to upload it via the github issue page (https://github.com/nicklockwood/Euclid/issues/110) instead of an email attachment? 

Failing that, if it's a plain text STL you can just paste the text into the form field.

**Comment by chessdenman** [comment]
[1Cil.txt](https://github.com/nicklockwood/Euclid/files/14064158/1Cil.txt)
hi It doesn't like me uploading a .stl file so I have renamed it .txt it is an ASCII not a binary.

**Comment by chessdenman** [comment]
Thanks so much.
That is fantastically helpful.
I am really enjoying the library.
I have a massive (and unwieldy) python application that I use to generate
gcode for a 3d printing application in clay. It links to blender at the
last moment to display a representation of the pot in the form of an elipse
that is extruded along the gcode tool path.
When you print in clay the layers are visible at about 1mm so its helpful
to see a visual representation of the final product.

The (somewhat over ambitious) masterplan is to rewrite the blender bit
using Euclid

I think I have worked out how to get bits of cgal to work inside a swift
program so that will allow for a fair bit of mesh analysis and processing.


Chess Denman
