### ISSUE TITLE
Problem with extrusion when using circle path with 25 segments

### ISSUE THREAD

**Issue by dharmeshrchauhan** [nicklockwood/Euclid#18]
When I try to do extrusion with circle path with 25 segments it is not showing cylinder ends as per attached screenshot. However it is working for other counts for segments though.

Following code will reproduce the problem:

        let path = Path.circle(radius: 0.50, segments: 25)
        let mesh = Mesh.extrude(path, depth: 0.25, faces: .default, material: UIColor.green)
        let geometry = SCNGeometry(mesh, materialLookup: {
            let material = SCNMaterial()
            material.diffuse.contents = $0 as? UIColor
            return material
        })
        let temporaryCylinderNode = SCNNode(geometry: geometry)
        scene.rootNode.addChildNode(temporaryCylinderNode)
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-01-22 at 20 18 45](https://user-images.githubusercontent.com/10988871/72904620-317cd300-3d55-11ea-9817-d55ae2441284.png)

**Comment by nicklockwood** [comment]
@dharmeshrchauhan thanks for reporting this. It's now fixed on the develop branch - I should have a new release out soon.

**Comment by dharmeshrchauhan** [comment]
thanks a lot,
I see that problem is no longer there in develop branch.
