### ISSUE TITLE
Tilted Extrusion

### ISSUE THREAD

**Issue by iwoj** [nicklockwood/Euclid#26]
I don't understand why some extrusions are tilted.

My code:
`currentFreedrawStroke!.geometry = SCNGeometry(Mesh.extrude( Path.circle(radius: strokeTubeRadius, segments: 6), along: Path.curve(pathPoints, detail: 2)))`

The two resulting meshes: [DAE file](https://www.dropbox.com/s/kznxmi6v2r7fyhv/Gesture%20Export%2019.dae?dl=0)

How do I ensure the above circle is always extruded perpendicular to the path?

**Comment by iwoj** [comment]
@nicklockwood Any idea how I can fix this?

**Comment by nicklockwood** [comment]
Fixed in 0.3.4
