### ISSUE TITLE
How to merged 2 translucent shape

### ISSUE THREAD

**Issue by icefox57** [nicklockwood/Euclid#3]
this is what i want to do , i found euclid maybe a solution for me.

https://stackoverflow.com/questions/55330969/how-to-merge-multiple-camera-projection-area-and-draw-on-a-planenode

And i tried to merge 2 shape , but seems not work for me .

2 shape have overlap, but not merged as i want , Actually, I just want the overlapping area have the same color.

![WechatIMG105](https://user-images.githubusercontent.com/1716737/55224911-6e1e9180-524c-11e9-9f43-168bd26cd727.jpeg)

this is the code .   

```
let path = Path([PathPoint(Vector(ptl), isCurved: false),
                             PathPoint(Vector(ptr), isCurved: false),
                             PathPoint(Vector(pbr), isCurved: false),
                             PathPoint(Vector(pbl), isCurved: false)])
            let mesh = Mesh.fill(path,material:UIColor.red.alpha(0.4))
            
            if let oldMesh = currentCapturedAeraMesh {
                currentCapturedAeraMesh = mesh.merge(oldMesh)
            } else {
                currentCapturedAeraMesh = mesh
            }
        
            let newNode = ARCapturedAeraNode(mesh:currentCapturedAeraMesh!)
            captureAreasPoints.append(mid)
            
            if let oldNode = sceneView.scene.rootNode.childNode(withName: "ARCapturedAeraNode",recursively: true) {
                sceneView.scene.rootNode.replaceChildNode(oldNode,with:newNode)
            } else {
                sceneView.scene.rootNode.addChildNode(newNode)
            }

```

could you help me , any idea or tips may help me a lot. thank you.

**Comment by nicklockwood** [comment]
@icefox57 Euclid's `merge` function just concatenates the polygons into a single Mesh, without trying to combine them.  Instead of

`mesh.merge(oldMesh)`

You probably want to use

`mesh.union(oldMesh)`

**Comment by nicklockwood** [comment]
Also, FYI, instead of

`PathPoint(Vector(ptl), isCurved: false)`

You can just write

`.point(Vector(ptl))`

**Comment by icefox57** [comment]
thank you very much
