### ISSUE TITLE
Non planar paths to Meshes

### ISSUE THREAD

**Issue by iwoj** [nicklockwood/Euclid#32]
Is there a way to turn non-planar paths into Meshes?

**Comment by nicklockwood** [comment]
That depends what you mean. How would you want the path to be converted to a mesh?

**Comment by iwoj** [comment]
I'm using `Mesh(Polygon(shape: Path(points))?.tessellate())` which works for any triangular polygon, and any path on xy, xz, zy planes (strangely not on arbitrarily oriented planes). However, I'd like to be able to draw more complex non-planar paths and have some way of tessellating a best guess of what the mesh should be. I don't really care what scheme it uses, I just want to resolve to some kind of mesh. A solid would be great, a surface would work too.

**Comment by nicklockwood** [comment]
Hmm, I think the code needed to do this is all there, but probably not exposed in any public API. You might need to add a version of tesselate that operates directly on a path instead of a Polygon, or add a Polygon constructor that doesn't check the points are planar.

**Comment by nicklockwood** [comment]
@iwoj this is now implemented in version 0.5.0.
