### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by netgfx** [nicklockwood/Euclid#33]
Hello, is there a documentation page to show the properties and syntax to create geometries etc?

**Comment by nicklockwood** [comment]
@netgfx this is covered briefly in the README file, e.g. the names of all the classes and methods. I haven't had time to fully document everything with examples yet, but hopefully the usage should be clear from the sample project and header documentation.

**Comment by chellem** [comment]
+1

**Comment by nicklockwood** [comment]
@netgfx thanks to the kind contributions of @heckj you can now find full documentation for Euclid at: https://nicklockwood.github.io/Euclid/documentation/euclid/ - let me know if you find anything incomplete or incorrect.
