### ISSUE TITLE
Encoding/Decoding 

### ISSUE THREAD

**Issue by iwoj** [nicklockwood/Euclid#34]
It looks like this library doesn’t support serialization/deserialization. How difficult would that be to add?

**Comment by nicklockwood** [comment]
You're right - this is something that should be supported. I'll look at adding it.

**Comment by iwoj** [comment]
How can I help?

**Comment by nicklockwood** [comment]
@iwoj I've made a start on it, and pushed a partial implementation to the [develop](https://github.com/nicklockwood/Euclid/tree/develop) branch. Let me know if that's what you were looking for.

**Comment by iwoj** [comment]
Excellent. Thank you. Although, the develop branch says the last commit was 9 days ago. Could you try pushing again?

**Comment by nicklockwood** [comment]
@iwoj sorry about that - not sure what happened. Try it now.

**Comment by nicklockwood** [comment]
@iwoj this has landed in 0.3.6 - let me know if you have any issues.

**Comment by iwoj** [comment]
Thanks for adding this. Much appreciated. I will test over the next few days.
