### ISSUE TITLE
Two objects in one mesh

### ISSUE THREAD

**Issue by gin66** [nicklockwood/Euclid#45]
Hello,

thanks for the great library and for sharing.

Currently I use your library for an App, which let javascript code drive Euclid to design 3d geometries. This approach is inspired by openscad and similar to your ShapeScript. An initial prototype looks promising. Now I have encountered a phenomenon, for which I am not sure, how to deal with it. I am using this javascript code, which could be one to one translated to swift-code:

```javascript
function build() {
    var c = cube({size: 6});
    var cy1 = cylinder({height: 8,radius: 2});
    var cy2 = cylinder({height: 2,radius: 8});
    cy1 = cy1.rotate({x:90})
    return c.subtract(cy1).subtract(cy2);
}
```

The result is apparent in this picture:

![A007A50C-E0C9-4F49-90C4-9ADDB61A8FDD](https://user-images.githubusercontent.com/5549373/120942506-a887f100-c729-11eb-83ab-e209bfe5ab2f.jpeg)

Now I am wondering:
- Is this expected ?
- How to identify this case: more than one object defined by one mesh ?
- How to derive the individual meshes of the objects ?

**Comment by nicklockwood** [comment]
Hi, this sounds like a cool project!

The result looks correct to me - you've subtracted a tall, narrow cyclinder from the cube, resulting in a circular hole, then subtracted a flat, wide cyclinder perpendicular to that, which cuts out a section of the resulting shape. You can maybe visualize this more easily by using merge instead of subtract to show all the shapes involved.

What were you expecting it to do?

As for indentifying meshes with more than one distinct closed shape in them, currently there is no function for this, but it probably wouldn't be hard for me to add. It would mean returning an array of meshes rather than one mesh from certain functions though.

**Comment by gin66** [comment]
Hello, thanks for the feedback. I am actually coming from FreeCAD. AFAIK, FreeCAD has the concept of a Body, which does not allow separated elements after a csg operation. The result provided by Euclid is, what I would expect logically. If this can be then exported to obj/stl and is a valid file, I have not tried, but have doubts. And what a slicer for 3d printing would make out of it, the same. A mesh representing one object will definitely work. Consequently supporting the individualization makes sense.

One function as extension to Mesh, which tries to transform one mesh into the disconnected submeshes would be a good addition in my eyes. Something like `Mesh.into_submeshes() -> [Mesh]`. If I study the concept of mesh, I probably could come up with a patch, too. 

BTW: Javascript works, but locating the origin of an error is with JavaScriptCore not possible. At least, what I know. So it will never be user friendly. Perhaps I move to lua.

**Comment by nicklockwood** [comment]
> FreeCAD has the concept of a Body, which does not allow separated elements after a csg operation

What would it do to prevent this? Return two separate objects?

> BTW: Javascript works, but locating the origin of an error is with JavaScriptCore not possible. At least, what I know. So it will never be user friendly. Perhaps I move to lua.

This is part of why I wrote my own language/parser for ShapeScript. If you know much about parsers, it wouldn't be hard to make a simple JavaScript interpreter using the same principles (ShapeScript is open source if you want to take a look).

**Comment by gin66** [comment]
> What would it do to prevent this? Return two separate objects?
No, it fails

> This is part of why I wrote my own language/parser for ShapeScript. If you know much about parsers, it wouldn't be hard to make a simple JavaScript interpreter using the same principles (ShapeScript is open source if you want to take a look).
Actually the lua integration works well (rudimentary) and better than javascript. In the moment I keep both. Support of ShapeScript or Openscad would be possible, but the required effort prevents it. Main reason, why I use an existing solution, because I don’t want to debug an own parser.

For the separation: I understand a polygon consist of vertices. And a vertex is the connection between two points defined by a position and a “normal”. And here I get lost, because normal is in my understanding a direction vector with length 1. So I miss the vertex length.

Anyway, the idea would be to loop through all polygons and build a map vertex-hash to polygon and polygon to vertex-hash. Then start with one polygon, identify all its vertices and add more polygons sharing the known vertices. Continue until no more polygons can be identified. Then one object has been found. If there are still more polygons, then restart the process for a potential third, fourth,… object. Makes sense ?

**Comment by nicklockwood** [comment]
> For the separation: I understand a polygon consist of vertices. And a vertex is the connection between two points defined by a position and a “normal”. And here I get lost, because normal is in my understanding a direction vector with length 1. So I miss the vertex length.

Vertex positions are in absolute coordinates, and vertices are always stored in anticlockwise order, so there's no need to define a vector between two vertices because it's implicit (you can subtract the vertex position from that of it's neighbour to get the separation between them).

The `normal` value represents the surface normal for that vertex. This is mainly for the purposes of lighting, so that you can determine whether the join between two polygons should be treated as a hard edge or a smooth curve (e.g. when using a polyhedron to approximate a smooth surface, such as a sphere).

**Comment by gin66** [comment]
Thanks for the feedback. I would assume, that the algorithm is O(n). The build up of the maps is linearly depending on the polygons. And removing the polygons from the table looks to me being linear, too.

For the vertex still not clear. So the vertex is actually a mesh point ?

**Comment by nicklockwood** [comment]
Ah, I misunderstood. You intend to build the vertex-polygon maps first and then find the connections, rather than finding the connections as you construct the map. In that case I believe you're correct.

**Comment by gin66** [comment]
In the meantime, I understand, that vertex is a point. I have mixed it up with an edge. 

I have not yet started, but I plan to not make a map of vertices but a map of edges and in addition count the number of occurrences. If there is an edge with an odd number of occurrences, then I assume, a mesh error has been detected.

What I am now wondering, if a hash of a vertex/edge with floating point values are generated. How can those hashes deliver identical result, if the points differ by less than epsilon - so are judged as being the same, but are for a hash totally different ?

**Comment by nicklockwood** [comment]
> I have not yet started, but I plan to not make a map of vertices but a map of edges and in addition count the number of occurrences. If there is an edge with an odd number of occurrences, then I assume, a mesh error has been detected.

This would be very useful. Currently I don't have functions for detecting whether a mesh is sealed, and boolean operations on unsealed meshes result in garbage output.

Note however that this is a harder problem than you think, because polygon edges do not always meet at a vertex. This scenario is possible after a CSG operation, and is not treated as an invalid mesh (although some programs won't accept meshes in this form, so a way of solving this would also be useful):

```
---------
|   |   |
---------
|     |
-------
```

> How can those hashes deliver identical result, if the points differ by less than epsilon

Conveniently, I quantize the positions of vertices by rounding to the nearest epsilon value anyway to avoid this problem. You will need to hash based on just the vertex position though, and ignore the normal, texcoord, etc.

**Comment by gin66** [comment]
First implementation with a handful of test cases is ok with individual mesh and union of two. But mesh as result of CSG subtract fails - as you have predicted...

Will see into this later

**Comment by gin66** [comment]
Actually for a polygon all combinations of vertices are used as an edge. Guess this is wrong. 

Are the vertices in the list of a polygon only connected with their neighbors ?

**Comment by gin66** [comment]
You have answered already:
> Vertex positions are in absolute coordinates, and vertices are always stored in anticlockwise order…

So already one bug identified to fix….

BTW: How to derive from a bunch of polygons a mesh again ?

**Comment by gin66** [comment]
apparently just `let m = Mesh(polygons)`

**Comment by gin66** [comment]
Have now an improved version, which works with cube separated in four pieces, but fails with a round hole in a cube. 

BTW: I remember, that a CSG subtract mixes materials. If a cube is material a and the hole is made from material b, then the result consists of material a at the outside and the hole is made of material b. I would have expected, that the inner hole is from material a, because the solid cube is wholly made from material a.

**Comment by nicklockwood** [comment]
It helps to think in terms of surfaces, not solids. When you subtract the cylinder, the surface of the resulting hole is formed from the cylinder, so it retains the material of the cylinder.

It wouldn't be hard to make the hole geometry take on the color on the cube if desired, but if you consider materials like a texture image and its associated texture coordinates, that would be much harder. You'd have to find a way to meaningfully map the existing texture of the cube over the arbitrary new surfaces formed by the CSG operation.

**Comment by gin66** [comment]
This means, the mesh has no defining material out of which new polygons can be created. But the cutting object has eventually a material property for each face being cut out. Clear. Thanks for explanation
