### ISSUE TITLE
Create custom 3d

### ISSUE THREAD

**Issue by chellem** [nicklockwood/Euclid#49]
> You can create a Mesh in Euclid by manually creating an array of Polygons, but that's pretty tedious

Can you please provide an example of this please ?

Am not seeing anything when trying to do this.

**Comment by nicklockwood** [comment]
@chellem can you post an example of what you've tried?

**Comment by chellem** [comment]
I have something like this.  Am sure that polygons and scene are not empty

```
let mesh = Mesh(polygons)
let geometry = SCNGeometry(mesh)
let node = SCNNode(geometry: geometry)
scene.rootNode.addChildNode(node)
```

@nicklockwood you've completed ignored my other issue. (Big thanks for the support )

**Comment by nicklockwood** [comment]
> @nicklockwood you've completed ignored my other issue. (Big thanks for the support )

I didn't realize you were the same user since you opened a new ticket. I'm not sure the sarcasm was called for.

**Comment by chellem** [comment]
@nicklockwood can you help ?
