### ISSUE TITLE
Prevent material from repeating in stencil

### ISSUE THREAD

**Issue by chellem** [nicklockwood/Euclid#52]
Hello @nicklockwood ,

I've been trying to use the `stencil` method which works fine except the material keeps on repeating while when seeing the material on the cube, I have one diagram per each side.

Can you help me with this?

**Comment by nicklockwood** [comment]
@chellem can you post a screenshot so I can better understand the issue?

**Comment by chellem** [comment]
@nicklockwood ,
I been able to make a stencil on my model but when trying to change its position, am getting repeats.

![IMG_0027](https://user-images.githubusercontent.com/570856/123591904-9e738280-d7fd-11eb-8bb7-dcafa899a696.jpg)
![IMG_A29993C1AC61-1 3](https://user-images.githubusercontent.com/570856/123591916-a29fa000-d7fd-11eb-84c8-17d9cf53682a.jpeg)

**Comment by nicklockwood** [comment]
@chellem that's very curious. Can you share your project? (send it to support@charcoaldesign.co.uk). I'll see if I can work out what's happening.

**Comment by chellem** [comment]
@nicklockwood, the project is quite big.

The part that am struggling is within the following lines:

```
let logo = UIImage(named: "logo")
let material = SCNMaterial()
material.diffuse.contents = logo
material.diffuse.wrapS = .repeat
material.diffuse.wrapT = .repeat
material.diffuse.contentsTransform = SCNMatrix4MakeScale(Float(size.x) * 0.2588, Float(size.y) * 0.475, Float(size.z))
let index: Float = 50
let denominator: Float = 1/index
let x = Double((image.size.width - CGFloat(index)) * (CGFloat)(denominator))
let y = Double((image.size.height - CGFloat(index)) * (CGFloat)(denominator))
let size = Vector(x, y, 1)
let cube = Mesh.cube(center: center, size: size, faces: .front, material: material)
let geometry = SCNGeometry(mesh.stencil(cube))
let node = SCNNode(geometry: geometry)
addChildNode(node)
```


Am trying to play with the material properties.  Change the diffuse wrap to .clamp, . mirror, .clampToBorder didn't help much. 
I also tries to play with the contentsTransform to get only one image per side, partial image always appears in some cases.

**Comment by chellem** [comment]
I have tried with 2 cases.  One is the stencil one (above) and the other is with a combination of `subtract` and `intersect`, while constructing a cube to place it into the subtract areas.  

In both cases, am getting the material applied to the cube only to continue onto the other model and thus having the repeating pattern.

**Comment by nicklockwood** [comment]
@chellem I think the repetition is happening because of the contentsTransform that you're applying (you can verify this by just rendering the cube on its own without the T-shirt).

If you just apply the texture directly to the cube without contentsTransform it shouldn't wrap. To reposition the texture on the T-shirt, you can then resize and reposition the cube itself.

**Comment by chellem** [comment]
Well, when viewing it with merge, it seems to be good but once I replace it with stencil, it repeats

![image](https://user-images.githubusercontent.com/570856/123637433-127a4e80-d82f-11eb-99a4-a9f969310d3d.png)

**Comment by nicklockwood** [comment]
Instead of a cube, what if you use an extruded rectangle instead? like this:

```swift
let cube = Mesh.extrude(.rectangle(width: x, height: y), material: material)
```

This should ensure only the front face is textured.

**Comment by nicklockwood** [comment]
On second thought, I'm not sure this can work actually. Stencil only takes the shape and material of the object, not texture coordinates. I'm not sure it can be used this way since the texture has a transparent background it will just make a cube-shaped hole with the logo floating inside it.

**Comment by nicklockwood** [comment]
Is there some way you can get the adidas logo as a vector shape, and then extrude that and use it as a stencil? That will work much better for this than a textured cube.

**Comment by chellem** [comment]
@nicklockwood, can you please give me some code example about what you mean above ?

**Comment by chellem** [comment]
@nicklockwood 

```
let logo = UIImage(named: "logo")
let material = SCNMaterial()
material.diffuse.contents = logo
material.diffuse.wrapS = .clamp
material.diffuse.wrapT = .clamp

let cube = Mesh.cube(center: center, size: size, faces: .front, material: material)
```

Why does the cube don't follow the material diffuse wrap property ?

I get it as repeated in every case. (`clamp`, `clampToBorder`, `mirror`)

**Comment by chellem** [comment]
> Is there some way you can get the adidas logo as a vector shape, and then extrude that and use it as a stencil? That will work much better for this than a textured cube.

You mean like use a SCNPlane, putting the image in it and then do the stencil ?

**Comment by nicklockwood** [comment]
> You mean like use a SCNPlane, putting the image in it and then do the stencil ?

No. I mean get something like an SVG copy of the logo, create a CGPath from that, create a ShapeScript path from that, and then extrude it, with a plain black material, and use that for the stencil.

**Comment by nicklockwood** [comment]
Alternatively, if you just want to apply the texture, you might be better off doing that in 2D, by using CoreGraphics to draw the logo onto the shirt texture before it is applied to the shirt model.

**Comment by chellem** [comment]
> Alternatively, if you just want to apply the texture, you might be better off doing that in 2D, by using CoreGraphics to draw the logo onto the shirt texture before it is applied to the shirt model.

If I draw the logo on the texture, I will not be repeated again ?

**Comment by nicklockwood** [comment]
> If I draw the logo on the texture, it will not be repeated again ?

It depends on how the T-shirt texture is mapped onto the T-shirt model, but as long as the T-shirt texture doesn't repeat, the logo won't either.

**Comment by chellem** [comment]
> > You mean like use a SCNPlane, putting the image in it and then do the stencil ?
> 
> No. I mean get something like an SVG copy of the logo, create a CGPath from that, create a ShapeScript path from that, and then extrude it, with a plain black material, and use that for the stencil.

Am giving a try to the first approach.  I got the CGPath from a SVG.  Now how to create that shapescript and proceed further ?

**Comment by chellem** [comment]
> > You mean like use a SCNPlane, putting the image in it and then do the stencil ?
> 
> No. I mean get something like an SVG copy of the logo, create a CGPath from that, create a ShapeScript path from that, and then extrude it, with a plain black material, and use that for the stencil.

Hi @nicklockwood, can you give me you contact details like email, skype or anything as such so that we can further talk about what I want to do ?

**Comment by nicklockwood** [comment]
@chellem you can use the support@charcoaldesign.co.uk address I posted earlier.

**Comment by nicklockwood** [comment]
> Am giving a try to the first approach. I got the CGPath from a SVG. Now how to create that shapescript and proceed further ?

You can convert the SVG to a 3D shape as follows:

```swift
let path = Path(cgPath: logo)
let shape = Mesh.extrude(path, material:  blackMaterial)
```

Then use stencil to "draw" the shape on the T-shirt, as you were trying to do with the cube before.
