### ISSUE TITLE
RealityKit Support

### ISSUE THREAD

**Issue by iwoj** [nicklockwood/Euclid#53]
RealityKit does not use SceneKit (while ARKit does). It would be great to add support for RealityKit in Euclid now that ModelEntities can be dynamically modified.

See 21:40 in https://developer.apple.com/videos/play/wwdc2021/10075/

**Comment by nicklockwood** [comment]
Yes, I was thinking the same thing. I'll look into it.

**Comment by iwoj** [comment]
Very poorly documented, but an important new feature of RealityKit. Not sure why Apple isn't making this a higher priority topic. (Also automated testing of Apple AR apps is almost impossible.)

Here are some relevant links:
https://maxxfrazer.medium.com/getting-started-with-realitykit-procedural-geometries-5dd9eca659ef
https://developer.apple.com/documentation/realitykit/creating_3d_content_with_reality_composer/adding_procedural_assets_to_a_scene
https://developer.apple.com/documentation/realitykit/meshdescriptor

**Comment by iwoj** [comment]
I just thought I'd bump this in case it's still in the running for your attention.

**Comment by nicklockwood** [comment]
@iwoj I'd still like to add this, but because it's not something I need myself it's pretty low down the priority list at the moment. If you'd be interested in attempting it yourself, even if it's just a prototype, I'd be happy to accept a PR and take over maintenance of it.

**Comment by nicklockwood** [comment]
@iwoj hey! I've pushed experimental RealityKit support to the [develop](https://github.com/nicklockwood/Euclid/tree/develop) branch. It's a WIP but I don't anticipate that the API will change significantly before release.

Please try it out and let me know if you find any problems.

**Comment by nicklockwood** [comment]
@iwoj landed in 0.6.0
