### ISSUE TITLE
Turning off assertions

### ISSUE THREAD

**Issue by iwoj** [nicklockwood/Euclid#54]
I'm having trouble debugging my code because Euclid runs its assertions when I use a Debug scheme configuration. Is there a way to suppress these without using a Release configuration?

**Comment by nicklockwood** [comment]
@iwoj the simplest thing would be to comment out or delete the assertions.

But Euclid isn't supposed to assert with valid data, so if you can tell me how to reproduce the assertions you're hitting, I'll try to fix them.

**Comment by iwoj** [comment]
I’m trying to import a mesh from an STL file and I hit an assertion that the mesh must be convex. 

Here’s the file. 

https://www.dropbox.com/s/uwjynw7u9wdon2c/fox2.stl?dl=0

________________________
Ian Wojtowicz
Graphite Design Labs
graphitedesignlabs.com
Makers of graphite.ar
Toll free: +1 877 266 2998

**Comment by nicklockwood** [comment]
@iwoj I'm not hitting this assertion when I try it. Can you share the code you are using to load the STL file?

**Comment by iwoj** [comment]
Looks like it happens when I try to run `mesh.detesselate()` on the imported mesh.

**Comment by nicklockwood** [comment]
@iwoj can you try with the latest develop branch? I'm not seeing an assertion.
