### ISSUE TITLE
Cube - width, height and lenght

### ISSUE THREAD

**Issue by Heinevolder** [nicklockwood/Euclid#63]
Hi! 

Thanks for a wonderful library

I'm having some trouble creating a cuboid with a specified width, depth, and height.
In the readme, you mention that it should be possible to generate a cuboid with different values for width, height, and/or depth. 

am I missing how this is done? 

Thanks again!

**Comment by nicklockwood** [comment]
@Heinevolder

```swift
let width = 1.0, height = 2.0, depth = 3.0
let cube  = Mesh.cube(size: Vector(width, height, depth))
```

**Comment by Heinevolder** [comment]
Oh - my bad! 

IDE didn't show the initializer with size as a vector for some reason.

**Comment by nicklockwood** [comment]
@Heinevolder it's overloaded with another version that takes a `Double` for size, so that's probably why.
