### ISSUE TITLE
Can we make Cross Section effect 

### ISSUE THREAD

**Issue by PrashantKT** [nicklockwood/Euclid#76]
is there any way that we can get this kind of effect 

https://www.youtube.com/watch?v=o8PdPdcbMzk 

Goal is - let's say two mesh are overlapping each other - I need to find the intersection on the plane  with 2d Path

**Comment by nicklockwood** [comment]
Yes, create a cube that us bigger than your mesh and then offset it and subtract from the mesh.

**Comment by nicklockwood** [comment]
If you only want the intersection (the shaded area in the video), not the cut-off shape itself, you could create a square shape and take the union of that and your mesh.

**Comment by iwoj** [comment]
Is Euclid sufficiently performant that it could achieve the same frame rates as the video?

**Comment by nicklockwood** [comment]
It depends on the complexity of the Mesh. It should be fast enough, but if not I'd be willing to work on optimizing it.

**Comment by PrashantKT** [comment]
@nicklockwood  Thank you , subtract is working like you have suggested 

    How can I Offset it , with translate ?  I have tried but It is always cutting from centre 

+ 

is there any way that I can get the path which is subtracted -  I need to draw 2d Path from area is intersected 

Like this image  - I need to draw border in 2d  

<img width="428" alt="Screenshot 2021-12-15 at 3 52 26 PM" src="https://user-images.githubusercontent.com/35359315/146169217-54d9d0bb-2613-48f6-b9fa-ccb9621b6057.png">

**Comment by nicklockwood** [comment]
> How can I Offset it , with translate ?  I have tried but It is always cutting from centre 

Yes, with translate.

> is there any way that I can get the path which is subtracted

There's not currently a way to get a Path from a mesh, but if you share your project I can take a look at how to do this for you. It may be possible by using detessellate function.

**Comment by PrashantKT** [comment]
Thank you for response 

Yes translate is working !! 

> There's not currently a way to get a Path from a mesh, but if you share your project I can take a look at how to do this for you. It may be possible by using detessellate function.


It can be your sample code - where we can load STL file (or any other mesh) - subtract cube  

Now  I need border  outline of remaining part - need to reflect in 2d UIView may be with BezierPath


![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2021-12-15 at 21 10 32](https://user-images.githubusercontent.com/35359315/146217830-de63989e-5ae3-4bf1-abe0-19fbe22050e5.png)


I have tried With reading vertex of model  using below link  - cut though from centre - find collided point  
But it is not accurate like your library 

https://gist.github.com/algal/8e31ce035af0aafebc3736661ae9e3cd

**Comment by nicklockwood** [comment]
Can you share the example model(s) you are testing with?

**Comment by PrashantKT** [comment]
Yes sure
[t6.stl.zip](https://github.com/nicklockwood/Euclid/files/7726001/t6.stl.zip)

**Comment by PrashantKT** [comment]
Update : 

@nicklockwood  

I am able to find these points
 
![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2021-12-17 at 12 04 14](https://user-images.githubusercontent.com/35359315/146500028-dac9f2d0-4418-48a3-b502-1647270d7be8.png)

From intersection function I am getting `bp`

But there are some other random points (other than border)

Now I need to draw 2d Arc using this points is there any way to do this ? - I can do project point of Scenekit - if camera is in somewhere else it will return wrong result 

```
func subtractPolygon(_ mesh: Mesh, isCancelled: CancellationHandler = { false }) -> ([Polygon],[Polygon],[Polygon])? {
        let intersection = bounds.intersection(mesh.bounds)
        guard !intersection.isEmpty else {
            return  nil
        }
        var aout: [Polygon]? = [], bout: [Polygon]?
        let ap = BSP(mesh, isCancelled).clip(
            boundsTest(intersection, polygons, &aout),
            .greaterThan,
            isCancelled
        )
        let bp = BSP(self, isCancelled).clip(
            boundsTest(intersection, mesh.polygons, &bout),
            .lessThan,
            isCancelled
        )
        
        return (aout!,ap,bp.map { $0.inverted()})
        
    }
```

Thanks in advance

**Comment by nicklockwood** [comment]
If you set a material on your cube, you can then filter the resultant polygons by that material and only have the vertices for those surfaces. That should make it easier.

**Comment by nicklockwood** [comment]
@PrashantKT if you'd like to try the latest build from the develop branch, I've added a new method to Mesh:

```swift
let mesh = Mesh.cube()
let plane = Plane.yz
let edges = mesh.edges(intersecting: plane)
```

This returns a Set of LineSegments that represent all the edges intersected by the plane. I think this will be the solution to your problem.

**Comment by PrashantKT** [comment]
@nicklockwood  Wow - That I will try definitely - Thank you for your all efforts
