### ISSUE TITLE
Node naming issues after the 3D model goes through Euclid

### ISSUE THREAD

**Issue by yuriynefedov** [nicklockwood/Euclid#88]
Hi! Our team is using Euclid to clip USDZ models, and we love it.

However, we recently noticed that after the model goes through Euclid and is further exported to SceneKit, the PNG texture files get renamed (see screenshots below).

Is this done internally by Euclid? If so, is there a way to prevent this renaming from happening?

Before:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/76853914/162378832-473d8a34-99e8-4f56-9f33-23953cee77a3.png">

After:
<img width="628" alt="image (1)" src="https://user-images.githubusercontent.com/76853914/162378914-81ab9317-4771-4296-8347-f8d5e5f28ec4.png">

**Comment by nicklockwood** [comment]
@yuriynefedov I'm just using Apple's own APIs for loading and saving USDZ, so I don't think there's any way I can influence this.

If you share a sample file I'll take a look and see if I can work out where the rename is happening though.

**Comment by nicklockwood** [comment]
@yuriynefedov any update on this? If you don't want to share your model publicly you can send it to support@charcoaldesign.co.uk

**Comment by yuriynefedov** [comment]
Thanks, @nicklockwood. Luckily we found a way to account for this in our scenario. This must be coming from Apple APIs indeed. Not a Euclid issue.
