### ISSUE TITLE
Is it possible to create a ring that can be animated from 0-360 degrees?

### ISSUE THREAD

**Issue by kemalenver** [nicklockwood/Euclid#9]
I'd like to create a tube geometry that can be animated from 0 -360 degrees over a set period of time.  A bit like a compass drawing a circle.  Is it possible to do something like this with Euclid?

**Comment by nicklockwood** [comment]
@kemalenver Euclid doesn't ave any animation capabilities, so you'd have to do it by creating the geometry afresh each frame. It should be possible to do this either by using `Mesh.loft()` to join a series of circular cross-sections, or by using `Mesh.lathe()` to create a torus, and then subtracting a wedge shape from it using CSG.
