### ISSUE TITLE
UNION operation result is with HOLE

### ISSUE THREAD

**Issue by PrashantKT** [nicklockwood/Euclid#92]
I am performing union operation with two STL 

The result of the union is with hole ,expected result is to merge both MODEL and create single model 

See the Image of Result 
![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-06-03 at 17 38 28](https://user-images.githubusercontent.com/35359315/171852224-61660027-745e-43f3-ba61-59b3ef5fd61d.png)

Attached the Result STL file  + Input model 
[RESULT.stl.zip](https://github.com/nicklockwood/Euclid/files/8832268/RESULT.stl.zip)
[Inputs Model.zip](https://github.com/nicklockwood/Euclid/files/8832293/Inputs.Model.zip)

Thanks in advance :)

**Comment by nicklockwood** [comment]
@PrashantKT the issue is that the IOScanupper_16.stl isn't watertight - it has holes in it. The union function only works with closed solids. Unfortunately I don't have a function that can fill these holes automatically at the moment.

**Comment by PrashantKT** [comment]
@nicklockwood  Okay Thanks - I will merge both with Scenekit

**Comment by nicklockwood** [comment]
@PrashantKT if you merely wish to combine the meshes you can use Euclid's Mesh.merge() function. I assumed you were using union because it removes overlapping polygons, but if you don't need that you can use merge.

**Comment by PrashantKT** [comment]
@nicklockwood  Okay I will try  Thanks
